# Generated by Django 5.0.6 on 2024-06-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('RA', models.CharField(max_length=30)),
                ('Curso', models.CharField(max_length=100)),
            ],
        ),
    ]
